export const FILE_UPLOAD_RULES = {
  MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB
  MAX_FILE_COUNT: 20,
  ALLOWED_EXTENSIONS: [
    'jpg',
    'jpeg',
    'png',
    // 'gif',
    // 'bmp',
    // 'mp4',
    // 'avi',
    // 'mkv',
    // 'mov',
    // 'wmv',
    // 'flv',
    // 'mp3',
    // 'wav',
    // 'flac',
    // 'alac',
    // 'aac',
    // 'txt',
    // 'doc',
    // 'docx',
    // 'xls',
    // 'xlsx',
    // 'ppt',
    // 'pptx',
    // 'pdf',
    // 'hwp',
    // 'zip',
    // 'rar',
    // 'alz',
  ],
};
export const ACCEPTED_IMAGE_TYPES = 'image/png, image/jpeg, image/jpg, image/PNG, image/JPEG, image/JPG';
